name: Terraform Plan

on:
  pull_request:
    paths:
      - '**/*.tf'
      - 'environments/**'
      - '.github/workflows/terraform-plan.yml'
      - '.github/workflows/terraform-apply.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    name: Plan ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, int, crt, prd]
    environment: ${{ matrix.environment }}
    env:
      TF_IN_AUTOMATION: true
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM OIDC token path
        run: |
          if [ -z "${AZURE_FEDERATED_TOKEN_FILE:-}" ]; then
            echo "AZURE_FEDERATED_TOKEN_FILE is not set after azure/login" >&2
            exit 1
          fi
          {
            echo "ARM_OIDC_TOKEN_FILE_PATH=$AZURE_FEDERATED_TOKEN_FILE"
            echo "ARM_OIDC_TOKEN_FILE=$AZURE_FEDERATED_TOKEN_FILE"
          } >> "$GITHUB_ENV"
          if [ -n "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:-}" ]; then
            echo "ARM_OIDC_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN" >> "$GITHUB_ENV"
          fi

      - name: Render backend config
        run: |
          cat <<'EOF' > backend.auto.tfbackend
          resource_group_name  = "${{ secrets.TF_RESOURCE_GROUP_NAME }}"
          storage_account_name = "${{ secrets.TF_STORAGE_ACCOUNT }}"
          container_name       = "${{ secrets.TF_CONTAINER_NAME }}"
          key                  = "states/${{ matrix.environment }}/terraform.tfstate"
          EOF

      - name: Terraform Init
        run: terraform init -backend-config=backend.auto.tfbackend

      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="environments/${{ matrix.environment }}/terraform.tfvars" \
            -var="environment=${{ matrix.environment }}" \
            -out="tfplan-${{ matrix.environment }}"

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: tfplan-${{ matrix.environment }}
