name: Terraform Plan

on:
  pull_request:
    paths:
      - '**/*.tf'
      - 'environments/**'
      - '.github/workflows/terraform-plan.yml'
      - '.github/workflows/terraform-apply.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    name: Plan ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, int, crt, prd]
    environment: ${{ matrix.environment }}
    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -backend-config="environments/${{ matrix.environment }}/backend.hcl"

      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="environments/${{ matrix.environment }}/terraform.tfvars" \
            -var="environment=${{ matrix.environment }}" \
            -out="tfplan-${{ matrix.environment }}"

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ matrix.environment }}
          path: tfplan-${{ matrix.environment }}
